### ISSUE TITLE
FERR-91 - Database document count summary information

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#18]
**Original Reporter:**  @markschiffner  
**Created:** 15/Jan/18 8:08 AM
# Description
1. On database selector, provide the count of documents visible to user based on role
2. On search/results page, provide the count of documents visible to the user
Options (Would it depend on data explorer role - wizard or search):
- If count is 0, simply do not include the database in the search screen for selection
- Display all databases and show 0 for databases when user can not see any documents
Maybe we can we determine if user does not have appropriate role(s), if there are no documents, etc. to provide more detailed information.  Remember, so environments are sensitive to visibility of documents (i.e. some users should not know that documents exist).  Maybe we have a setting that allows reporting different ways depending on the program requirements or security requirements.

**Comment by mhuang-ml** [comment]
Hi @markschiffner,

I've got a quick proof of concept with changes applied.  I need to go in and refactor it since I was just testing overloading the database name that was returned and concatenating the document count, but I wanted to get your feedback on this to see if this is similar to what you had in mind with adding the document count that is visible to the user.

![documentcountconcatenation](https://user-images.githubusercontent.com/16652599/41815328-64aad804-7735-11e8-8c25-de49338ddf87.png)

Let me know what you think about this and then if it's acceptable to you then I'll continue moving down this path.

**Comment by markschiffner** [comment]
@mhuang-ml I think that looks great.  Is it showing count of documents user has access to or total documents?

**Comment by mhuang-ml** [comment]
@markschiffner, it's showing the count of the documents that the user has access to.  I was double checking the existing database call to see the permissions & roles that the existing database call was using.  I also double checked this by creating a new document that only one (1) role had access two and I had two (2) different users, one with the role added and one without the role added.  With the user with the role added then the document count for Data-Explorer-content is (8680) and then with the user without the role, then the count is (8679).

I appreciate the feedback though!  I'll finish refactoring the code with the required changes, but before I went that far, I wanted to get feedback on the POC changes first.
