### ISSUE TITLE
FERR-88 - JAR deploy not working if admin password is not "admin"

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#27]
**Original Reporter:**  @damonfeldman  
**Created:** 	11/Dec/17 11:26 AM
# Description
I changed my admin password and re-ran the deploy, but it fails with a 401 (not authorized).

I suspect the gradle.properties for the project is being picked up from inside the jar (there's a copy in META-INF/com.marklogic.data-explorer).

A workaround is to include the admin password as a Java override property:

`-DmlPassword=<NewAdminPassword>`

Note, I aslo tried

`$ java -jar data-explorer.jar --mlUsername admin --mlPassword=<newAdminPwd> deploy`

But that also failed.

**Comment by josvr** [comment]
@rjrudin any comments

**Comment by rjrudin** [comment]
Put the command first, and don't use an equals symbol in the command line arguments; do what you're doing for the username, i.e. 

    java -jar data-explorer.jar deploy --mlUsername admin --mlPassword test

The required format is shown by running the jar without a command:

    java -jar data-explorer.jar 

Or: 

    java -jar data-explorer.jar --help (or -h)

Also, where do you see gradle.properties in the exploded jar? There's a META-INF/com.marklogic.dataexplorer/data-explorer.properties file, which is intended to be there - it has default values for the properties, which includes mlPassword=admin and mlUsername=admin.

I'm going to close this, as I believe the fix is to put the command first and not use equals with the command line arguments.
